version: '3'
services:
  sw-dev:
    working_dir: /var/www/sw
    build: ./docker/php73-swoole/
    image: sw-dev
    container_name: es
    ports:
      - 19501:9501
    volumes:
      - ./app:/var/www/sw
    entrypoint: "php /var/www/sw/easyswoole start"
    expose:
      - 9501
  sw-nginx:
    image: nginx
    container_name: easy-nginx
    volumes:
      - ./docker/nginx15/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx15/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/sw
    links:
      - sw-dev
    ports:
      - 19502:81