version: '3'
services:
  sw-dev:
    working_dir: /var/www/sw
    build: ./docker/php73-swoole/
    image: sw-dev
    container_name: es
    ports:
      - 19501:9501
    volumes:
      - ./app:/var/www/sw
    entrypoint: "php /var/www/sw/easyswoole start"
